---
- name: Configure App
  hosts: app
  become: true
  vars:
    db_host: "{{ hostvars[groups['db'][0]]['network_interface.0.address'] }}"
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/otus/db_config
        owner: otus
        group: otus
    - name: enable puma
      systemd: name=puma enabled=yes

  handlers: 
    - name: reload puma
      systemd: name=puma state=restarted
